<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="WorkflowSyntaxTests.fs" />
    <Compile Include="RuleATests.fs" />
    <Compile Include="RuleBTests.fs" />
    <Compile Include="ProjectReferenceXmlTests.fs" />
    <Compile Include="RuleBExceptionTests.fs" />
    <Compile Include="RuleBWorkflowTests.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/FS.GG.Org.Policy/FS.GG.Org.Policy.fsproj" />
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
</Project>
